package com.demo.model;

import com.demo.model.base.BaseRolesPermissions;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RolesPermissions extends BaseRolesPermissions<RolesPermissions> {
	public static final RolesPermissions dao = new RolesPermissions();
}
