package com.demo.model;

import com.demo.model.base.BaseUserRoles;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRoles extends BaseUserRoles<UserRoles> {
	public static final UserRoles dao = new UserRoles();
}
