package com.demo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFile<M extends BaseFile<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setFilename(java.lang.String filename) {
		set("filename", filename);
	}

	public java.lang.String getFilename() {
		return get("filename");
	}

	public void setFilesize(java.lang.String filesize) {
		set("filesize", filesize);
	}

	public java.lang.String getFilesize() {
		return get("filesize");
	}

	public void setFilelines(java.lang.String filelines) {
		set("filelines", filelines);
	}

	public java.lang.String getFilelines() {
		return get("filelines");
	}

}
